### ISSUE TITLE
Overlap ORFs density threshold 

### ISSUE THREAD

**Issue by BenjaminGuinet** [urmi-21/orfipy#11]
Hello, have you developed a way to allow a certain size of overlaps between ORFs in order to maximize the density of longest ORFs along  scaffolds? 

Tanks you very much for this soft by the way, very efficient and easy to use.

All the best

Ben

**Comment by urmi-21** [comment]
Hi @Niwradel! Thanks for the positive feedback! I am not sure if I understand your question completely. Right now orfipy doesn't report overlapping/nested ORFs in the same frame. I don't understand "maximize the density of longest ORFs along scaffolds" 
Can you please provide an example? I am interested in knowing.

**Comment by BenjaminGuinet** [comment]
Hello, here is an example : 
```

ORF1          |--------|
ORF2                 |----|
ORF3                                 |---------|
ORF4                                  |--------|
```

In that example, I wanted to know if orfipy authorize overlapping ORFs (with threshold) as in **ORF1** and **ORF2**? or do it takes only the longest (**ORF1**?).

And as in **ORF3** and **ORF4**  the overlapping is too high, so you keep the longest (**ORF3**?)

**Comment by urmi-21** [comment]
Thanks for the example.  If  ORF1 and ORF2 are in different frames then both ORFs are reported (given they match you min and max length parameter).

If ORF1 and ORF2 are in the same frame then first start and first stop is reported as ORF regardless of the length. Below example ORF2 is longer but since its START is in-frame inside another ORF it is not considered as a START.

e.g. assuming same frame, 

ORF1    |----------|
ORF2                 |-----------------------------------------------------|

ORF 1 has leftmost (towards 5') START and STOP so ORF1 is reported. 

**NOTE** ORF2 may still be reported by orfipy if you set the `--partial-5` flag. First codon in ORF2 will be the one right after the STOP in ORF1. partial-5 means ORFs without a start codon but a stop codon. Similarly there is a flag `--partial-3` 

Here is a small example:

```
>s1
ATGGGGGGGTTTAAATAGTTTCCCGTTCCCTTTAAATTTGCCATTGGTGCCTTTAAATGGCGTTTTAAACGTTAG
```

```
orfipy --min 0 --outdir out  s.fa | grep frame=1

Processed 1 sequences in 0.21 seconds
s1      0       15      ID=s1_ORF.1;ORF_type=complete;ORF_len=15;ORF_frame=1;Start:ATG;Stop:TAG 0       +
```

**With --partial-5"**

```
orfipy --min 0 --outdir out  --partial-5 s.fa | grep frame=1

Processed 1 sequences in 0.21 seconds
s1      0       15      ID=s1_ORF.1;ORF_type=complete;ORF_len=15;ORF_frame=1;Start:ATG;Stop:TAG 0       +
s1      18      72      ID=s1_ORF.2;ORF_type=5-prime-partial;ORF_len=54;ORF_frame=1;Start:NA;Stop:TAG   0       +
```
