### ISSUE TITLE
Python 3.9 support using conda

### ISSUE THREAD

**Issue by EnzoAndree** [urmi-21/orfipy#2]
Hello Urminder!

Amazing work! I didn't think that Cython could reach such speed. I will keep it in mind for my next projects.

I wanted to report that conda fails to install orfipy when you have Python 3.9 installed. I strongly believe that orfipy should not have problems in Python 3.9.

Do you plan to enable Python 3.9 support in the conda recipe?

Best regards!
Enzo.

**Comment by urmi-21** [comment]
Hi @EnzoAndree 
Thank you for reporting the issue. I am not sure if bioconda supports python 3.9 (https://github.com/bioconda/bioconda-recipes/issues/24215), they just recently added support for python3.8.

I did not specifically limit orfipy for python<3.9 in the recipe so i think we have to wait till it is enabled in bioconda. Definitely want to provide orfipy for python 3.9 through bioconda.

BTW `pip install orfipy` works for python 3.9 so you can still use orfipy in python 3.9.

I will close this issue here and add it to *todo* list. If you have any comments please feel free to reopen.

**Comment by urmi-21** [comment]
Another cause might be the dependencies for orfipy not available for python3.9 through conda. I will take a look at what might be the problem exactly.

**Comment by EnzoAndree** [comment]
Actually, Python 3.9 is only available in the conda-forge channel.

I enclose the conda output if it is useful

```
$ conda install orfipy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                      
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - orfipy -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

`pip install orfipy` works very well 👍
